const Common = {
    PERMISSIONS: {VIEW : "VIEW", EDIT: "EDIT", MANAGE: "MANAGE", CREATE_VAULTS: "CREATE_VAULTS", MANAGE_MEMBERS: "MANAGE_MEMBERS", MANAGE_ORGANIZATION: "MANAGE_ORGANIZATION"},
    DEFAULT_ROLES: {OWNER: "OWNER", ADMIN: "Admin", EVERYONE: "Everyone", ME: "Just Me"},
    STATUS: {PENDING: "PENDING", ACCEPTED: "ACCEPTED", REFUSED: "REFUSED"}
}

export default Common;