# Generated by Django 5.0.4 on 2024-05-15 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationHasVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.organization')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.organizationvault')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('MANAGE', 'Manage'), ('MEMBERS', 'Members'), ('CREATE_VAULTS', 'Create Vaults'), ('MANAGE_MEMBERS', 'Manage Members'), ('MANAGE_ORGANIZATION', 'Manage Organization')], default='VIEW', max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.member')),
                ('organizationHasVault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.organizationhasvault')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MemberInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REFUSED', 'Refused')], default='PENDING', max_length=20)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.organization')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.role')),
            ],
        ),
        migrations.CreateModel(
            name='MemberHasRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.member')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.role')),
            ],
        ),
        migrations.CreateModel(
            name='RoleOrganizationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('MANAGE', 'Manage'), ('MEMBERS', 'Members'), ('CREATE_VAULTS', 'Create Vaults'), ('MANAGE_MEMBERS', 'Manage Members'), ('MANAGE_ORGANIZATION', 'Manage Organization')], max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.role')),
            ],
        ),
        migrations.CreateModel(
            name='RoleVaultPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('MANAGE', 'Manage'), ('MEMBERS', 'Members'), ('CREATE_VAULTS', 'Create Vaults'), ('MANAGE_MEMBERS', 'Manage Members'), ('MANAGE_ORGANIZATION', 'Manage Organization')], max_length=50)),
                ('organizationHasVault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.organizationhasvault')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.role')),
            ],
        ),
    ]
