# Generated by Django 5.0.4 on 2024-05-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vault',
        ),
    ]
