# Generated by Django 5.0.4 on 2024-05-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_delete_vault'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('size', models.BigIntegerField(default=0)),
                ('organizations', models.BigIntegerField(default=0)),
                ('vaults', models.BigIntegerField(default=0)),
                ('users', models.BigIntegerField(default=0)),
                ('requests', models.BigIntegerField(default=0)),
                ('items', models.BigIntegerField(default=0)),
            ],
        ),
    ]
