# Generated by Django 5.0.4 on 2024-05-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_organization_size_delete_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationvault',
            name='vault',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entities.vault'),
            preserve_default=False,
        ),
    ]
