# Generated by Django 5.0.4 on 2024-05-27 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_chat_chatinvite_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinvite',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entities.chat'),
            preserve_default=False,
        ),
    ]
