# Generated by Django 5.0.4 on 2024-05-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_remove_rolepermission_vault_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpermission',
            name='vault',
        ),
        migrations.AddField(
            model_name='memberpermission',
            name='organizationHasVault',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entities.organizationhasvault'),
            preserve_default=False,
        ),
    ]
