# Generated by Django 5.0.4 on 2024-05-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_remove_memberpermission_vault_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationvault',
            name='vault',
        ),
    ]
