# Generated by Django 5.0.4 on 2024-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_remove_organizationvault_vault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpermission',
            name='permission',
            field=models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('Manage', 'Manage')], default='VIEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('Manage', 'Manage')], max_length=50),
        ),
    ]
