# Generated by Django 5.0.4 on 2024-06-05 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('entities', '0006_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatter1', to='authentication.qeepuser'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.qeepuser'),
        ),
        migrations.AlterField(
            model_name='chatinvite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_inviter', to='authentication.qeepuser'),
        ),
        migrations.AlterField(
            model_name='chatinvite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.qeepuser'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.qeepuser'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.qeepuser'),
        ),
        migrations.AlterField(
            model_name='memberinvite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='authentication.qeepuser'),
        ),
        migrations.AlterField(
            model_name='memberinvite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.qeepuser'),
        ),
    ]
