# Generated by Django 5.0.4 on 2024-05-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_alter_memberpermission_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpermission',
            name='permission',
            field=models.CharField(choices=[('VIEW', 'view'), ('EDIT', 'edit'), ('MANAGE', 'manage')], default='VIEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('VIEW', 'view'), ('EDIT', 'edit'), ('MANAGE', 'manage')], max_length=50),
        ),
    ]
