# Generated by Django 5.0.4 on 2024-05-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_memberpermission_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationvault',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
