# Generated by Django 5.0.4 on 2024-05-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_alter_organizationvault_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpermission',
            name='permission',
            field=models.CharField(choices=[('VIEW', 'view'), ('EDIT', 'edit'), ('MANAGE', 'manage'), ('MEMBERS', 'members'), ('CREATE_VAULTS', 'create_vaults'), ('MANAGE_MEMBERS', 'manage_members'), ('MANAGE_ORGANIZATION', 'manage_organization')], default='VIEW', max_length=50),
        ),
        migrations.CreateModel(
            name='RoleOrganizationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'view'), ('EDIT', 'edit'), ('MANAGE', 'manage'), ('MEMBERS', 'members'), ('CREATE_VAULTS', 'create_vaults'), ('MANAGE_MEMBERS', 'manage_members'), ('MANAGE_ORGANIZATION', 'manage_organization')], max_length=50)),
                ('organizationHasVault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.organizationhasvault')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.role')),
            ],
        ),
        migrations.CreateModel(
            name='RoleVaultPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'view'), ('EDIT', 'edit'), ('MANAGE', 'manage'), ('MEMBERS', 'members'), ('CREATE_VAULTS', 'create_vaults'), ('MANAGE_MEMBERS', 'manage_members'), ('MANAGE_ORGANIZATION', 'manage_organization')], max_length=50)),
                ('organizationHasVault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.organizationhasvault')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.role')),
            ],
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
