# Generated by Django 5.0.4 on 2024-05-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_alter_memberpermission_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleorganizationpermission',
            name='organizationHasVault',
        ),
    ]
