# Generated by Django 5.0.4 on 2024-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_memberinvite_inviter'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinvite',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
