# Generated by Django 5.0.4 on 2024-05-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_memberinvite_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinvite',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('REFUSED', 'refused')], default='PENDING', max_length=20),
        ),
    ]
