# Generated by Django 5.0.4 on 2024-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_memberinvite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
