# Generated by Django 5.0.4 on 2024-06-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('vault', models.CharField()),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='items/')),
                ('size', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
