# Generated by Django 5.0.4 on 2024-05-20 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vault',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entities.organizationvault'),
            preserve_default=False,
        ),
    ]
