# Generated by Django 5.0.4 on 2024-05-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_item_vault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='vault',
        ),
    ]
