# Generated by Django 5.0.4 on 2024-05-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_item_vault'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vault',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
