# Generated by Django 5.0.4 on 2024-05-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_item_vault'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
