# Generated by Django 5.0.4 on 2024-05-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_item_size_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
