# Generated by Django 5.0.4 on 2024-05-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_item_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
