# Generated by Django 5.0.4 on 2024-05-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_item_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vault',
            field=models.CharField(),
        ),
    ]
