# podman/docker build -t reconciliation .
# podman/docker run -it -v .:/app reconciliation

FROM debian:bookworm

RUN apt update && \
    apt install -y tmux build-essential libcrypto++-dev libcrypto++-doc libcrypto++-utils

ENV INSIDE_CONTAINER=true
ENV DIRECTORY_MultiMachine_MessageHandler="cv_qokd_ldpc_multi_machine_messageHandler" 
ENV EXECUTABLE_MultiMachine_MessageHandler="compile_run_cv_qokd_ldpc_message_handler.sh"

WORKDIR /app

ENTRYPOINT bash -c "cd $DIRECTORY_MultiMachine_MessageHandler && chmod +x $EXECUTABLE_MultiMachine_MessageHandler && ./$EXECUTABLE_MultiMachine_MessageHandler; exec bash"

